# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb622221e3a2754731a351ee76fb14c10e092ed6bff16e7d06d4ffb069a97ec30aaa404235eec59149f5fcf6ee5d7c052e24f53999e63cd9d589862387a9ca4c

test:
  secret_key_base: 8644d5f07a439b426eb59663f46e910138be032973b02f00c9a35f4e32714a424d93d518e737c2933dc2a7158625e6babe2306b7ee34911b35c735ffef93ec5a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
